/* eslint-disable */
// Prototype-only data for the People Matching Concept deck.
// Synthetic Chadwick-like examples. This is not a database schema contract.

const MATCHING_ORG = {
  name: "Chadwick Alumni Network",
  shortName: "Chadwick",
  context: "Palos Verdes and Songdo",
};

const MATCHING_VIEWER = {
  id: "mina-han",
  name: "Mina Han",
  initials: "MH",
  school: "Chadwick International",
  year: 2024,
  role: "Senior",
  city: "Songdo, KR",
  currentFocus: "Choosing between product design, UX research, and product management internships.",
  notificationCadence: "Weekly digest only",
};

const MATCHING_PEOPLE = [
  {
    id: "mina-han",
    name: "Mina Han",
    initials: "MH",
    school: "Chadwick International",
    year: 2024,
    role: "Senior",
    employer: "Student",
    city: "Songdo, KR",
    tags: ["UX research", "Product", "College transition"],
    bio: "Exploring product and design paths before college. Looking for honest advice, not a formal mentor yet.",
  },
  {
    id: "daniel-cho",
    name: "Daniel Cho",
    initials: "DC",
    school: "Chadwick School",
    year: 2011,
    role: "Group Product Manager",
    employer: "Northstar Health",
    city: "Los Angeles, CA",
    tags: ["Product management", "Healthcare", "Korea-US careers"],
    bio: "Open to quick advice for students and recent grads thinking about product careers. Best for async questions first.",
  },
  {
    id: "sora-kim",
    name: "Sora Kim",
    initials: "SK",
    school: "Chadwick International",
    year: 2016,
    role: "UX Research Lead",
    employer: "Kakao Mobility",
    city: "Seoul, KR",
    tags: ["UX research", "Interview prep", "Korean tech"],
    bio: "Can help with UX research portfolios, user interviews, and making Korean tech applications less intimidating.",
  },
  {
    id: "evan-park",
    name: "Evan Park",
    initials: "EP",
    school: "Chadwick School",
    year: 2008,
    role: "Founder",
    employer: "Harbor Robotics",
    city: "Palos Verdes, CA",
    tags: ["Startups", "Robotics", "Fundraising"],
    bio: "Happy to talk to alumni building something technical, especially before they raise money or hire friends.",
  },
  {
    id: "lia-ross",
    name: "Lia Ross",
    initials: "LR",
    school: "Chadwick School",
    year: 2018,
    role: "Analyst",
    employer: "Pacific Ridge Capital",
    city: "Santa Monica, CA",
    tags: ["Finance", "Internships", "First job"],
    bio: "Can answer one-off questions about finance internships, analyst recruiting, and the first year out of college.",
  },
  {
    id: "jason-lee",
    name: "Jason Lee",
    initials: "JL",
    school: "Chadwick International",
    year: 2022,
    role: "Computer Science Student",
    employer: "KAIST",
    city: "Daejeon, KR",
    tags: ["CS", "College applications", "Research labs"],
    bio: "Recently went through college applications and lab recruiting. Wants advice on whether to work in LA next summer.",
  },
  {
    id: "aisha-morgan",
    name: "Aisha Morgan",
    initials: "AM",
    school: "Chadwick School",
    year: 2014,
    role: "Admissions Counselor",
    employer: "Westbridge College",
    city: "Pasadena, CA",
    tags: ["College essays", "Admissions", "First-gen support"],
    bio: "Open to essay review and college decision conversations for Chadwick students when capacity allows.",
  },
  {
    id: "noah-choi",
    name: "Noah Choi",
    initials: "NC",
    school: "Chadwick International",
    year: 2019,
    role: "Software Engineer",
    employer: "Stripe",
    city: "San Francisco, CA",
    tags: ["Software engineering", "Fintech", "Referrals"],
    bio: "Can help students understand technical interviews, internships, and what a useful referral request looks like.",
  },
];

const SAVED_QUESTIONS = [
  {
    id: "sq-ux-product",
    ownerId: "mina-han",
    title: "Should I aim for UX research or product management internships?",
    summary: "I like user interviews and product strategy, but I do not know which path fits a first internship.",
    context: "College starts in the fall. Mina wants a lightweight conversation with someone who has seen both tracks.",
    status: "Active",
    privacy: "Private to matching",
    expiresIn: "23 days",
    cadence: "Weekly digest only",
    tags: ["UX research", "Product", "Internships"],
  },
  {
    id: "sq-la-summer",
    ownerId: "jason-lee",
    title: "Is LA a good place for a first software internship?",
    summary: "I am comparing Seoul, San Francisco, and Los Angeles for summer engineering work.",
    context: "Jason is looking for practical advice before he starts sending applications.",
    status: "Quietly watching",
    privacy: "Private to matching",
    expiresIn: "41 days",
    cadence: "In-app only",
    tags: ["Software engineering", "Los Angeles", "Internships"],
  },
  {
    id: "sq-founder-deck",
    ownerId: "evan-park",
    title: "Who can review a student robotics pitch before a demo day?",
    summary: "A younger alum asked for founder feedback before pitching a robotics project.",
    context: "This is a helper-side saved intent: Evan wants to find students he can support.",
    status: "Helper intent",
    privacy: "Visible only to suggested matches",
    expiresIn: "14 days",
    cadence: "Do not email",
    tags: ["Robotics", "Pitch deck", "Founder advice"],
  },
];

const HELPER_OFFERS = [
  {
    helperId: "daniel-cho",
    openToAdvice: true,
    openToMentorship: true,
    preferredStyle: "Async first, then a 20-minute call if there is a fit.",
    topics: ["Product management", "Korea-US career moves", "Healthcare startups"],
    capacity: { active: 2, maxActive: 4, pending: 1, maxPending: 3 },
  },
  {
    helperId: "sora-kim",
    openToAdvice: true,
    openToMentorship: false,
    preferredStyle: "One-off advice and portfolio comments on weekends.",
    topics: ["UX research", "Portfolio review", "Korean tech interviews"],
    capacity: { active: 0, maxActive: 0, pending: 2, maxPending: 4 },
  },
  {
    helperId: "aisha-morgan",
    openToAdvice: true,
    openToMentorship: true,
    preferredStyle: "Essay feedback in batches. Mentorship for a small number of seniors.",
    topics: ["College essays", "Admissions", "Decision review"],
    capacity: { active: 3, maxActive: 3, pending: 1, maxPending: 2 },
  },
  {
    helperId: "noah-choi",
    openToAdvice: true,
    openToMentorship: false,
    preferredStyle: "Short tactical questions. No long-term mentorship this month.",
    topics: ["Technical interviews", "Fintech", "Referral etiquette"],
    capacity: { active: 0, maxActive: 0, pending: 0, maxPending: 5 },
  },
];

const RECOMMENDATIONS = [
  {
    id: "rec-daniel-mina",
    direction: "asker_to_helper",
    questionId: "sq-ux-product",
    personId: "daniel-cho",
    title: "This person may be relevant",
    actionLabel: "Ask for advice",
    confidence: 91,
    trigger: "Helper updated topics 2 days ago",
    source: "Product topic + Korea-US career path",
    reasons: [
      "Daniel lists product management and Korea-US career moves as help topics.",
      "His preferred style starts with async advice, which fits Mina's low-commitment question.",
      "He has room for one more pending request this week.",
    ],
  },
  {
    id: "rec-sora-mina",
    direction: "asker_to_helper",
    questionId: "sq-ux-product",
    personId: "sora-kim",
    title: "This person may be relevant",
    actionLabel: "Ask for advice",
    confidence: 88,
    trigger: "New profile joined matching pool",
    source: "UX research + Songdo/Seoul proximity",
    reasons: [
      "Sora is open to one-off UX research advice.",
      "Her profile mentions portfolios and user interviews.",
      "She is near Songdo and has Chadwick International context.",
    ],
  },
  {
    id: "rec-aisha-mina",
    direction: "asker_to_helper",
    questionId: "sq-ux-product",
    personId: "aisha-morgan",
    title: "Useful but at capacity",
    actionLabel: "Save for later",
    confidence: 72,
    trigger: "Question matched an admissions-adjacent concern",
    source: "College decision context",
    reasons: [
      "Aisha can help with college transition questions.",
      "She is currently at mentorship capacity.",
      "This is better saved than sent immediately.",
    ],
  },
  {
    id: "rec-noah-jason",
    direction: "helper_to_asker",
    questionId: "sq-la-summer",
    personId: "jason-lee",
    helperId: "noah-choi",
    title: "You might be able to help",
    actionLabel: "Offer advice",
    confidence: 84,
    trigger: "Saved question matched your helper topics",
    source: "Software internship + California move",
    reasons: [
      "Jason is weighing a summer engineering internship in California.",
      "Your helper topics include technical interviews and internships.",
      "A one-off reply would likely be enough.",
    ],
  },
  {
    id: "rec-evan-student",
    direction: "helper_to_asker",
    questionId: "sq-founder-deck",
    personId: "mina-han",
    helperId: "evan-park",
    title: "You might be able to help",
    actionLabel: "Offer a review",
    confidence: 79,
    trigger: "Helper intent found a related student project",
    source: "Founder advice + student project",
    reasons: [
      "Mina follows the robotics club and saved a product question.",
      "Evan wants to help student builders before demo day.",
      "The system needs explicit permission before surfacing Evan to Mina.",
    ],
  },
];

const EVENT_CONNECTION_SUGGESTIONS = [
  {
    id: "evt-songdo-coffee",
    eventTitle: "Songdo Alumni Coffee",
    eventWhen: "May 18, 2026",
    location: "Songdo, KR",
    copy: "People who also attended. We do not know who you talked to, so this is just a reminder.",
    cadence: "One in-app prompt + one digest mention",
    people: [
      {
        personId: "sora-kim",
        reason: "Also attended and works in UX research.",
        suggestedNote: "I noticed we were both at Songdo Alumni Coffee and would enjoy staying connected.",
      },
      {
        personId: "jason-lee",
        reason: "Also attended and recently asked about internships.",
        suggestedNote: "I think we were both at the Songdo coffee meetup. Happy to connect here if useful.",
      },
    ],
  },
  {
    id: "evt-pv-founder-night",
    eventTitle: "Palos Verdes Founder Night",
    eventWhen: "May 9, 2026",
    location: "Palos Verdes, CA",
    copy: "Reconnect from an event, only if a name feels familiar.",
    cadence: "In-app only",
    people: [
      {
        personId: "evan-park",
        reason: "Host and open to founder advice.",
        suggestedNote: "Thanks for hosting Founder Night. I would like to stay connected through BridgeCircle.",
      },
      {
        personId: "lia-ross",
        reason: "Also attended and helps with internships.",
        suggestedNote: "I saw you were also at Founder Night. It would be great to connect here.",
      },
    ],
  },
];

const THANK_YOU_NOTES = [
  {
    id: "ty-mina-daniel",
    fromId: "mina-han",
    toId: "daniel-cho",
    threadTitle: "Product internship direction",
    body: "Daniel helped me understand the difference between a product manager internship and a UX research internship. The advice made the next step feel much clearer.",
    privateByDefault: true,
    senderAllowsSpotlight: true,
    recipientApproved: false,
    spotlightStatus: "Awaiting recipient approval",
  },
  {
    id: "ty-jason-noah",
    fromId: "jason-lee",
    toId: "noah-choi",
    threadTitle: "Technical interview prep",
    body: "Noah shared a practical way to prepare for technical interviews without over-studying. I am keeping this private because it includes application details.",
    privateByDefault: true,
    senderAllowsSpotlight: false,
    recipientApproved: false,
    spotlightStatus: "Private only",
  },
  {
    id: "ty-lia-aisha",
    fromId: "lia-ross",
    toId: "aisha-morgan",
    threadTitle: "College essay review",
    body: "Aisha gave thoughtful essay feedback and made the revision process feel less stressful.",
    privateByDefault: true,
    senderAllowsSpotlight: true,
    recipientApproved: true,
    spotlightStatus: "Approved for spotlight",
  },
];

const NOTIFICATION_PREVIEW = [
  {
    channel: "In-app",
    label: "New match found",
    example: "Sora Kim may be relevant to your saved question.",
    defaultOn: true,
  },
  {
    channel: "Email digest",
    label: "Weekly summary",
    example: "3 possible helpers, 1 post-event reconnect reminder.",
    defaultOn: true,
  },
  {
    channel: "Popup",
    label: "Rare prompts only",
    example: "Used after a completed session or immediately after an event page visit.",
    defaultOn: false,
  },
];

window.BC_MATCHING_DATA = {
  org: MATCHING_ORG,
  viewer: MATCHING_VIEWER,
  people: MATCHING_PEOPLE,
  savedQuestions: SAVED_QUESTIONS,
  helperOffers: HELPER_OFFERS,
  recommendations: RECOMMENDATIONS,
  eventConnectionSuggestions: EVENT_CONNECTION_SUGGESTIONS,
  thankYouNotes: THANK_YOU_NOTES,
  notificationPreview: NOTIFICATION_PREVIEW,
};
